FROM node:16-alpine AS build-env

WORKDIR /frontend

COPY . .

RUN npm install
RUN npm run build

FROM nginx:alpine

# Remove the default configuration to not conflict with our new config file
RUN rm -rf /etc/nginx/conf.d/*
RUN cp -r /build/dist/* /usr/share/nginx/html/